# Site
repository: ehho0916/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Woo Taeho
title: Network/System Engineer
email: ehho0916@yonsei.ac.kr
website: https://github.com/ehho0916

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: ehho0916
linkedin_username: woo-taeho
# instagram_username: your_instagram
# twitter_username: your_twitter
# youtube_username: your_youtube

# Additional icon links
additional_links:
  - title: Yonsei University
    icon: fas fa-university
    url: https://www.yonsei.ac.kr

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  안녕하세요, Woo Taeho입니다. 현재 네트워크/시스템 엔지니어로 활동하고 있으며, 시스템 운영, 네트워크 설계 및 관리, 클라우드 인프라 운영 경험을 보유하고 있습니다.

  <mark>Linux</mark>, <mark>Networking</mark>, <mark>Cloud (AWS, GCP)</mark>, <mark>Scripting</mark> 등에 강점을 가지고 있으며, 다양한 프로젝트에서 협업과 문제 해결 역량을 발휘했습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Network Automation Toolkit
        link: https://github.com/ehho0916/network-automation-toolkit
        additional_links:
          - title: ehho0916/network-automation-toolkit
            icon: fab fa-github
            url: https://github.com/ehho0916/network-automation-toolkit
        quote: >
          Automating routine network configuration tasks to improve consistency and reduce human error.
        description: | 
          Python과 Ansible을 활용해 네트워크 장비의 설정을 자동화하는 툴킷을 개발했습니다. CLI 파서, Config Push 기능 등을 포함하고 있으며, 실제 운영 환경에 적용해 효율을 개선했습니다.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Yonsei University
        link: https://yonsei.ac.kr
        sub_title: Network/System Engineer (Research Lab)
        caption: March 2022 - Present
        quote: >
          Supporting research and production systems with robust, secure, and scalable infrastructure.
        description: | 
          연구실 서버 인프라를 설계하고 운영하며 네트워크 구성, 리눅스 서버 관리, 백업 및 보안 정책을 관리했습니다. 
          다양한 오픈소스 솔루션과 클라우드 인프라(AWS, GCP)를 연동하여 실험 및 서비스 환경을 구축했습니다.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Yonsei University
        caption: 2017 - 2022
        sub_title: BSc in Computer Science (or Information & Communication Engineering)
        quote: >
          Yonsei University, one of Korea's top universities, with strong reputation for engineering and technology.
        description: | 
          Yonsei에서 컴퓨터 과학/정보통신 공학을 전공하며 네트워크, 시스템 프로그래밍, 운영체제 등 핵심 과목을 수강했습니다.
          졸업 프로젝트와 연구실 활동을 통해 실무 역량을 쌓았습니다.

  - title: A Little More About Me
    layout: text
    content: | 
      업무 외 시간에는 다음과 같은 취미를 즐깁니다:
      - 클라이밍
      - 게임
      - 여행
      - [유튜브에서 기술 영상 보기](https://www.youtube.com)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag